baseurl = "http://www.chrischoy.net/" # Must end with /
languageCode = "en-us"
title = "Chris Choy"
theme = "introduction"
enforce_ssl = false
builddrafts = false
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
# disqusshortname   = "xxx" # Enable Disqus for comments
# googleAnalytics   = "xxx"

[permalinks]
fixed = ":title/"
blog  = "blog/:slug/"

[params]
author = "Christopher Choy" # Full name shows on blog post pages
firstname = "Chris" # First name shows in introduction on main page
tagline = "Student. Programmer. Innovator." # Appears after the introduction
introheight = "fullheight" # Input either 'medium' or 'large' or 'fullheight'
theme = "dark" # Choose 'light' or 'dark'
avatar = "img/profile.JPG" # Path to image in static folder eg. img/avatar.png, or comment out to remove
email = "contact@chrischoy.net" # Shows in contact section, or leave blank to omit
localtime = true # Show your current local time in contact section
timezone = "America/Chicago" # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 EST"
cachebuster = true # Add the current unix timestamp in query string for cache busting css assets
description = "The personal webpage of Christopher Choy"
faviconfile = "img/favicon.ico"
highlightjs = true # Syntax highlighting
lang = "en"
footertext = "© Christopher Choy 2017" #Text to show in footer (overrides default text)
fadein = true # Turn on/off the fade-in effect

showprojects    = true # Show Projects section on home page

showblog = false # Show Blog section on home page
showallposts = false # Set 'true' to list all posts on home page, or set 'false' to link to separate blog list page
showlatest = true # Show latest blog post summary
sharebuttons = true # On post pages, show share this social buttons

# Share buttons
sharetwitter = true
sharefacebook = true
sharepinterest = false
sharegoogleplus = false

# This is your projects section. Three images of the same dimensions will look the nicest. If images are omitted, text links will be shown.
project1link = "http://femmes.io/"
project1img = "img/femmes-2.jpg"
project1title = "FEMMES"

project2link = "#"
project2img = "img/tea-party-games.jpg"
project2title = "Tea Party Games"

project3link = "https://csil.cs.uchicago.edu"
project3img = "img/csil.jpg"
project3title = "CSIL"


# Social icons appear in introduction and contact section. Add as many more as you like.
# Find icon names here: http://fontawesome.io/cheatsheet/

[[params.social]]
url = "https://www.facebook.com/chris.choy.52"
icon = "facebook"

[[params.social]]
url = "https://github.com/cchoy96"
icon = "github"

[[params.social]]
url = "https://linkedin.com/in/cchoy96"
icon = "linkedin"
